### ISSUE TITLE
SNYK: golang.org/x/net Denial of Service (DoS)

### ISSUE THREAD

**Issue by chbul** [equinor/terraform-azurerm-service-bus#11]
### Summary of issue
- Severity: high
- Affected versions of this package are vulnerable to Denial of Service (DoS) in the implementation of the HTTP/2 protocol. An attacker can cause a denial of service (including via DDoS) by rapidly resetting many streams through request cancellation.

[Link](https://cwe.mitre.org/data/definitions/400.html) to detailed description

**Comment by helenakallekleiv** [comment]
Fixed in https://github.com/equinor/terraform-azurerm-service-bus/pull/26
