### ISSUE TITLE
SNYK: google.golang.org/grpc Denial of Service (DoS)

### ISSUE THREAD

**Issue by chbul** [equinor/terraform-azurerm-service-bus#13]
### Summary of issue
- Severity: high
- Affected versions of this package are vulnerable to Denial of Service (DoS) in the implementation of the HTTP/2 protocol. An attacker can cause a denial of service (including via DDoS) by rapidly resetting many streams through request cancellation.

[Link](https://learn.snyk.io/lesson/redos/?authenticate=automatic&_gl=1*etqw6s*_ga*MjAzNTIwMTA5LjE2NzY4OTUxOTQ.*_ga_X9SH3KP7B4*MTcwMDU2OTU3MS45LjEuMTcwMDU3NjgxOS4wLjAuMA..) to detailed description

**Comment by helenakallekleiv** [comment]
Fixed in https://github.com/equinor/terraform-azurerm-service-bus/pull/26
