### ISSUE TITLE
SNYK: github.com/satori/go.uuid Insecure Randomness

### ISSUE THREAD

**Issue by chbul** [equinor/terraform-azurerm-service-bus#14]
### Summary of issue
- Severity: high
- Affected versions of this package are vulnerable to Insecure Randomness producing predictable UUID identifiers due to the limited number of bytes read when using the g.rand.Read function.

Note: This vulnerability was introduced on the master branch of satori/go.uuid after version 1.2.0. This was fixed on commit d91630c8510268e75203009fe7daf2b8e1d60c45.

[Link](https://learn.snyk.io/lesson/insecure-randomness/?authenticate=automatic&_gl=1*xbvfev*_ga*MjAzNTIwMTA5LjE2NzY4OTUxOTQ.*_ga_X9SH3KP7B4*MTcwMDU2OTU3MS45LjEuMTcwMDU3NjgxOS4wLjAuMA..) to detailed description

**Comment by helenakallekleiv** [comment]
Closing, se comment in https://github.com/equinor/terraform-azurerm-service-bus/issues/12#issuecomment-1959077221
