### ISSUE TITLE
SNYK: github.com/docker/distribution Type Confusion

### ISSUE THREAD

**Issue by chbul** [equinor/terraform-azurerm-service-bus#22]
### Summary of issue
- Severity: medium
- Affected versions of this package are vulnerable to Type Confusion. Documents that contain both “manifests” and “layers” fields can be interpreted as either a manifest or an index in the absence of an accompanying Content-Type header. If a Content-Type header changes between two pulls of the same digest, a client may interpret the resulting content differently.

[Link](https://learn.snyk.io/lesson/type-confusion/?authenticate=automatic&_gl=1*123flfd*_ga*MjAzNTIwMTA5LjE2NzY4OTUxOTQ.*_ga_X9SH3KP7B4*MTcwMDU2OTU3MS45LjEuMTcwMDU3NjgxOS4wLjAuMA..) to detailed description

**Comment by helenakallekleiv** [comment]
Fixed in https://github.com/equinor/terraform-azurerm-service-bus/pull/26
